version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes: 
            - .:/code     # um Code dynamisch einzubinden: mounted . auf /code im container
    redis:
        image: "redis:alpine"